# REQUIRED CHANGES
# Edit next line to provide your own name.
title: Deo Gratias Bibila | Personal Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://deobibila99.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
## Specify the theme using any of the css files in css/techfolio-theme
techfolio-theme: default.css
## Specify the formatting for triple backquote code sections.
rouge-theme: github.css

# DON'T CHANGE THE FOLLOWING (unless you know what you're doing)
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist

name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change this if your repo's default branch is different

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub's hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Ensure compatibility with your site

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  

